### PR TITLE
Json parameter parsing

### PR DESCRIPTION
**Pull request by lperanni**
Hello first, i am a fresh web dev intern and this is my first pull request to a package like this. My mentor encouraged me to explore around a bit. Anyways, i needed cron to be able to parse a json parameter string and i did some digging and experimenting. Sry if it's not up to standards i gave it my best  😅

### CODE REVIEW

**Comment by ncb000gt** [comment]
Interesting idea.

Can you make sure all the tests pass. Also, can you add some testing around failure cases, not just expected cases? Thanks!

**Comment by lperanni** [comment]
I improved the code and added a few tests that cover a few bad cases as well (out of bounds, non existing params)

**Comment by ncb000gt** [comment]
Just a heads up, I haven't forgotten about this. I've just been insanely busy. I'll be reviewing this when I get a chance. Thanks for the effort on it.

**Comment by joeflateau** [comment]
parsing json seems out of scope of this project, but i love the idea of accepting an object instead of a string. i have a utility object => cron string function i use in every project w/ node cron

**Comment by ncb000gt** [comment]
I have taken a look and agree with @joeflateau, that i'm not sure this makes sense for the module, at least in its current state. I've been considering a larger refactor for a long time and may include some of what you've done in here in that. I'll leave this open for a few days for the dialog.

@lperanni Please let me know if you vehemently disagree. Thanks.

**Comment by bozzmob** [comment]
This is a very interesting PR. Good job @lperanni .

**Comment by intcreator** [comment]
I agree that this is out of scope for this project. if you need to parse JSON for cron it should be easy enough to to yourself beforehand

**Pull request closed without merging**
