### PR TITLE
update vulnerable packages

### PR DESCRIPTION
**Pull request by intcreator**
updated a bunch of packages that have vulnerabilities (just in package-lock.json for now, I can try updating package.json to fix the rest if you like). I can also see if I can get builds running again. is that the workflow that's awaiting approval?

Additional vulns are all Jest deps. the fix involves updating to Jest 27.5.1 which I can attempt as long as someone's willing to double check the tests afterward

### CODE REVIEW

**Comment by ncb000gt** [comment]
Can you update `package.json` to reflect the changes? Thanks!

**Comment by intcreator** [comment]
sure, I updated `package.json` and split one of the tests into two different tests. this was necessary since Jest 27 requires `done()` to be called only once per test. each of the two tests makes sure that the cron job can be stopped either using `job.stop()` from outside the cron job or `this.stop()` from inside. let me know if we need another test to make sure both can be used at the same time with no side effects

**Comment by intcreator** [comment]
I ran `npm i` and for good measure `npm ci` locally and it looks like all issues there are resolved

**Comment by intcreator** [comment]
I also updated the workflow Node versions to reflect [currently supported Node versions](https://nodejs.org/en/about/releases/)

**Pull request merged**
