### PR TITLE
Allow soft warning when a hard error isn't required.

### PR DESCRIPTION
**Pull request by ncb000gt**
GH-467 GH-478 GH-469 GH-470 GH-497 GH-498

Signed-off-by: Nick Campbell <nicholas.j.campbell@gmail.com>

### CODE REVIEW

**Comment by utick** [comment]
any update?

**Comment by Bilonik** [comment]
Update?

**Comment by ncb000gt** [comment]
My hesitation with this PR is that it effectively reverts the change that was made to prevent infinite loops inside the cron tool. Of course this only happens in certain cases, and isn't all the time, but I want to support a better option. I'm thinking of making a change to this that resets the time by which the tool runs. I'll post here when I've settled on the best way to add this. Once I have a solution for this I'll push the code.

**Comment by aphix** [comment]
@ncb000gt FYI it looks like this PR will always make `softTimeout === true` because of the or pipes (`||`) here: [`e928c8c` (#499)](https://github.com/kelektiv/node-cron/pull/499/commits/e928c8c103d8f590cdabafbc47f24eab1e9314a9#diff-d823dceb04482ab55e5004eebb53fc1cR58)

In line 58 of `lib/job.js` in the PR: `softTimeout = cronTime.softTimeout || true`

If provided initially via an object, the softTimeout option `{softTimeout: false}` would always be coerced to true based on the above logic, which would then be passed into the CronTime constructor.

**Comment by intcreator** [comment]
if anyone is curious on the decision making behind closing this PR check out [this comment on #686](https://github.com/kelektiv/node-cron/pull/686#issuecomment-1678110690)

**Pull request closed without merging**
