### PR TITLE
Migrate from Moment.js to Luxon

### PR DESCRIPTION
**Pull request by bvigursky**
Moment.js library takes a lot of space, in comparison with it Luxon is much more compact.
Luxon also works much better with DST. Most of the time, DST shifts will happen without having to do anything about it and everything will just work. It gives possibility to remove the code related to solving DST problems, that happen during using Moment.js.

### CODE REVIEW

**Comment by ncb000gt** [comment]
If I'm not mistaken, Luxon breaks backwards compatibility for the month. I read through the Luxon and moment differences quickly, do you know if that's going to be an issue?

**Comment by bvigursky** [comment]
> If I'm not mistaken, Luxon breaks backwards compatibility for the month. I read through the Luxon and moment differences quickly, do you know if that's going to be an issue?

Sorry, I did not quite understand about what backward compatibility you are talking about. Could you clarify please?

**Comment by leonardfactory** [comment]
Looking at Luxon [support matrix](https://moment.github.io/luxon/docs/manual/matrix.html), seems Zone supports (plus basic features) are guaranteed with Node 8+ .
Talking about month, moment.js use 0-indexed while luxon uses 1-indexed, but @bvigursky PR seems to handle it checking `date.month() - 1 in this.month`.

**Comment by ncb000gt** [comment]
I am a little concerned about the use of this module for web applications and the support matrix of Luxon, but it's probably ok. I'm going to merge this but make it a major version bump. I'm going to try to incorporate a few other changes into the version so it may take a little bit of time to land in npm. Thanks for the work here.

**Comment by Unitech** [comment]
Awesome, glad this sponsored PR has been merged :+1:

**Comment by naorye** [comment]
When it will be published?

**Pull request merged**
