### PR TITLE
Eslint update to latest + lint fixes

### PR DESCRIPTION
**Pull request by tudorbarbu**

### CODE REVIEW

**Comment by tudorbarbu** [comment]
While fixing the build for node 14, by adding the checks from the new n(ode) plugin which was required by one of the new packages, I've found out that the test files are also published
```
~/git/node-cron/tests/cron.test.js
  2:23  error  "sinon" is not published  n/no-unpublished-require

~/git/node-cron/tests/crontime.test.js
  2:23  error  "sinon" is not published  n/no-unpublished-require
```
  This lint error states that sinon is required in the test files, and as the test files are published, it should be a dependency of the package when publishing.
  What do you think would be the best course of action?

1.   Unpublish the tests
2. Ignore this rule for the test files

**Comment by intcreator** [comment]
I think we should unpublish the tests. if someone wants to know the library works they can clone the repo or look at the automatic checks

thanks for the PR by the way! and for fixing the merge conflict

**Comment by tudorbarbu** [comment]
I've made the changes for only publishing the lib
The linter also passes now

**Comment by intcreator** [comment]
thanks! would you mind explaining the changes to .eslintrc?

**Comment by tudorbarbu** [comment]
> thanks! would you mind explaining the changes to .eslintrc?

By using `"extends": [
		"standard",
		"plugin:jest/recommended",
		"plugin:import/recommended",
		"plugin:n/recommended",
		"plugin:prettier/recommended",
		"plugin:promise/recommended"
	]`, it will enable all the recommended linter options defined by those plugins
Additional rules can be enabled by appending the rules section if desired.
The plugins list is no longer needed since it's handled by the extend part.
As it can be seen from the lint fixes, more rules are now enabled (thanks to the recommended configs)
Furthermore, rules will need less manual updates since configs will be updated when something important appear and the dependency is updated

**Comment by intcreator** [comment]
thanks for your work @tudorbarbu! just merged. nice to see all the `let`s and `const`s instead of `var`s!

**Pull request merged**
