### PR TITLE
Add utcOffset support

### PR DESCRIPTION
**Pull request by matsukaz**
I wanted to use CronJob with utcOffset support, so I've added utcOffset to the CronJob constructor.

### CODE REVIEW

**Comment by ncb000gt** [comment]
This is great. Would you mind resolving the conflicts and I'll merge it in again? Thanks!

**Comment by matsukaz** [comment]
@ncb000gt Hi, sorry for leaving this pr for such a long time X(
I've fixed the conflicts.
Could you plz check it again ?

**Comment by matsukaz** [comment]
@ncb000gt Could you plz check my pr again?
I'll be glad if this pr get merged.

**Comment by ncb000gt** [comment]
@matsukaz Sorry for the delay, too much going on. This has been landed. Thanks!

**Pull request merged**
